### ISSUE TITLE
counter doesn't appear to have updated

### ISSUE THREAD

**Issue by ddemaio** [openSUSE/countdown.o.o#22]
@lnussel I changed the counter, but doesn't appear to be tracking. I checked at 12:00 (10:00 UTC) today to see if it would change from 2 to 1 day, but it didn't change. I image if it changes at  14:00 (12:00 UTC) today that https://counter.opensuse.org is still using the older code.

**Comment by hellcp** [comment]
There were some issues with deployment this year.

CC @cboltz @darix

**Comment by lnussel** [comment]
the cron job probably needs to be switched to hourly rendering

**Comment by cboltz** [comment]
Fixed, see my mails in the heroes ML yesterday.
